name: "Testes Unitários com Mocha"

on:
  push:
  workflow_dispatch:

jobs:
  unit-tests:
    runs-on: ubuntu-24.04

    steps:
      - name: Fazendo checkout do projeto para o runner
        uses: actions/checkout@v4

      - name: Instalando Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Instalando Yarn
        run: npm install -g yarn

      - name: Instalando Dependências
        run: yarn

      - name: Executando Testes Unitários
        run: yarn mocha ./testes/trabalho-final.js --reporter mochawesome
        
      - name: Publicando Relatório de Execução dos Testes
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: relatorio
          path: mochawesome-report
